"""
daemon/advisor/template_engine.py — Explanation and YAML rule generation.

Takes a DetectionCandidate + replay figures and produces:
  1. proposed_yaml_rule — the candidate policy.yaml network_rules snippet
  2. reasoning_text     — the filled template string from WARDEN_SPEC.md §9

Both are deterministic, traceable functions of the detection data.
No LLM involvement. Every number in reasoning_text maps directly to a
ledger query result — full auditability.

WHY template (not LLM): from WARDEN_SPEC.md §9 — "because detection relies
on structured data (exact counts, thresholds, matched fields), the reasoning
for any proposal is generated by filling in a fixed template with real ledger
numbers. This guarantees full auditability — every number traces back to a
ledger query."
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

import yaml

if TYPE_CHECKING:
    from daemon.advisor.detection_scanner import DetectionCandidate


def _is_hostname(destination: str) -> bool:
    """Return True if destination looks like a hostname rather than an IP.

    Heuristic: a hostname contains at least one letter. An IP address
    consists only of digits and dots (IPv4) or hex/colons (IPv6).
    This is intentionally simple — the sidecar already parsed SNI from TLS
    handshakes, so a destination with letters is a hostname.
    """
    return bool(re.search(r"[a-zA-Z]", destination))


def build_proposed_rule(candidate: "DetectionCandidate") -> str:
    """Generate a YAML rule snippet that would BLOCK the detected (binary, destination).

    The proposed rule is a named BLOCK rule, promoting the detected pair from
    the catch-all default_action:flag to an explicit BLOCK entry. This is the
    tightening direction — always permissive_change=0.

    Returns:
      A YAML string representing a single network_rules entry.
    """
    # Decide whether to match by hostname or dst_ip
    if _is_hostname(candidate.destination):
        match_key = "hostname"
    else:
        match_key = "dst_ip"

    rule = {
        "match": {
            "binary": [candidate.binary],
            match_key: [candidate.destination],
            "dst_port": ["*"],
        },
        "action": "block",
        "risk": "high",
        "reason": (
            f"Auto-proposed: {candidate.occurrence_count} FLAGs detected "
            f"in Phase 3 advisor scan (exact_match_frequency_v1)"
        ),
    }

    # yaml.dump wraps in a list; we want a bare mapping for easy insertion
    # into network_rules. Return the serialised single rule dict.
    return yaml.dump(rule, default_flow_style=False).strip()


def build_reasoning_text(
    candidate: "DetectionCandidate",
    replay_changed: int,
    replay_total: int,
    n_threshold: int = 10,
    window_hours: float = 6.0,
) -> str:
    """Fill the §9 explanation template with real detection and replay numbers.

    Template (from WARDEN_SPEC.md §9):
      Pattern detected: N occurrences of `binary` → `destination`
      with FLAG verdict over T hours
      (threshold: N=10, T=6h).
      Proposed rule: see YAML below.
      Historical replay: would have changed A of B events from FLAG to BLOCK.

    Every number in the output is derived from real ledger data — no invented
    or approximated values.
    """
    # Calculate actual window width from the matched events
    actual_hours = (candidate.window_end - candidate.window_start) / 3600.0

    axis_display = "IP" if candidate.detection_axis == "ip" else "hostname"

    lines = [
        f"Pattern detected: {candidate.occurrence_count} occurrences of "
        f"`{candidate.binary}` \u2192 `{candidate.destination}` (matched via {axis_display}) "
        f"with FLAG verdict over {actual_hours:.1f} hours "
        f"(threshold: N={n_threshold}, T={window_hours:.0f}h).",
        f"Proposed rule: see YAML below.",
        f"Historical replay: would have changed {replay_changed} of {replay_total} "
        f"events from FLAG to BLOCK.",
    ]
    return "\n".join(lines)


def is_permissive(proposed_yaml_rule: str) -> bool:
    """Return True if the proposed rule expands permissions (action: allow).

    In the initial Phase 3 build, the advisor only proposes BLOCK rules
    (permissive_change=0 always). This function exists to make the check
    explicit and testable, and to future-proof the approval CLI for the
    case where ALLOW-expanding rules are eventually proposed.
    """
    try:
        rule = yaml.safe_load(proposed_yaml_rule)
        action = rule.get("action", "block") if isinstance(rule, dict) else "block"
        return action.lower() == "allow"
    except Exception:
        # Malformed YAML — treat as non-permissive (conservative)
        return False
