#!/usr/bin/env python3
"""
sidecar/interceptor.py — Warden Network Sidecar Interceptor

CONTRACT: This is the entry point for the warden-sidecar container.
It intercepts outbound network traffic from the jail using NFQUEUE.
"""

import os
import sys
import argparse
import subprocess
import atexit
import yaml
import json
import socket
import time

try:
    import netfilterqueue  # type: ignore
except ImportError:
    pass

from daemon.parser.packet_parser import PacketParser
from daemon.inspectors.network_inspector import NetworkInspector
from daemon.rules.engine import RuleEngine
from daemon.inspectors.base import Decision

POLICY_PATH = os.environ.get("WARDEN_POLICY_PATH", "daemon/rules/policy.yaml")
WARDEN_SOCKET_PATH = os.environ.get("WARDEN_SOCKET_PATH", "/tmp/warden_ipc/warden.sock")
NFQUEUE_NUM = 0


def verify_environment() -> bool:
    """Verify the container environment before attempting NFQUEUE work."""
    ok = True
    socket_dir = os.path.dirname(WARDEN_SOCKET_PATH)
    if not os.path.isdir(socket_dir):
        print(f"[warden-sidecar] ERROR: IPC directory {socket_dir!r} does not exist.", file=sys.stderr, flush=True)
        ok = False

    try:
        import netfilterqueue  # type: ignore # noqa: F401
    except ImportError as e:
        print(f"[warden-sidecar] ERROR: cannot import netfilterqueue: {e}", file=sys.stderr, flush=True)
        ok = False
    except OSError as e:
        print(f"[warden-sidecar] ERROR: netfilterqueue import raised OSError: {e}", file=sys.stderr, flush=True)
        ok = False

    return ok


def setup_iptables(queue_num: int) -> None:
    """
    Insert iptables rule to redirect traffic to NFQUEUE.

    WHY OUTPUT (not FORWARD): The sidecar shares the jail's network namespace
    (`network_mode: "service:jail"` in docker-compose.yml). From the perspective
    of this shared namespace, packets generated by the jail's processes originate
    locally. They therefore traverse the OUTPUT chain. The FORWARD chain only
    applies to packets being routed *through* the namespace from one interface
    to another, which is not what the jail is doing.
    """
    print(f"[warden-sidecar] Inserting iptables rule on OUTPUT chain for queue {queue_num}...", flush=True)
    subprocess.run(
        ["iptables", "-I", "OUTPUT", "-j", "NFQUEUE", "--queue-num", str(queue_num)],
        check=True
    )


def teardown_iptables(queue_num: int) -> None:
    """Remove the iptables rule on exit."""
    print(f"[warden-sidecar] Removing iptables rule for queue {queue_num}...", flush=True)
    subprocess.run(
        ["iptables", "-D", "OUTPUT", "-j", "NFQUEUE", "--queue-num", str(queue_num)],
        check=False  # Ignore errors if rule is already gone
    )


def build_callback(parser: PacketParser, inspector: NetworkInspector, engine: RuleEngine):
    """Factory to build the packet callback with closed-over dependencies."""
    def packet_callback(packet) -> None:
        raw_bytes = packet.get_payload()
        
        # 1. Parse
        try:
            parsed = parser.parse(raw_bytes)
        except Exception:
            # If we absolutely cannot parse it, drop it as malformed.
            packet.drop()
            return

        # 2. Inspect
        verdict = inspector.inspect(parsed)
        
        # 3. Evaluate
        final_verdict = engine.evaluate(parsed, [verdict] if verdict else [])
        
        # 4. Log via IPC UDS
        try:
            payload = {
                "timestamp": time.time(),
                "verdict": {
                    "decision": final_verdict.decision.value,
                    "reason": final_verdict.reason,
                    "source_inspector": final_verdict.source_inspector,
                    "confidence": final_verdict.confidence
                },
                "parsed_action": {
                    "dst_ip": parsed.dst_ip,
                    "dst_port": parsed.dst_port,
                    "protocol": parsed.protocol,
                    "hostname_or_sni": parsed.hostname_or_sni,
                    "direction": parsed.direction,
                    "raw_input": parsed.raw_input
                }
            }
            with socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM) as s:
                s.sendto(json.dumps(payload).encode("utf-8"), WARDEN_SOCKET_PATH)
        except Exception as e:
            # Fallback gracefully if the socket is missing or full
            print(f"[warden-sidecar] Warning: failed to send event to socket: {e}", file=sys.stderr)
        
        # 5. Enforce
        if final_verdict.decision == Decision.ALLOW:
            packet.accept()
        else:
            packet.drop()
            
    return packet_callback


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Read packet bytes from stdin instead of NFQUEUE")
    args = parser.parse_args()

    if not args.dry_run and not verify_environment():
        print("[warden-sidecar] environment checks FAILED", file=sys.stderr, flush=True)
        sys.exit(1)

    print("[warden-sidecar] Loading components...", flush=True)
    
    with open(POLICY_PATH, "r") as f:
        policy_doc = yaml.safe_load(f)
    network_rules = policy_doc.get("network_rules", [])

    # Instantiate the 3 pillars of the interception loop
    packet_parser = PacketParser()
    inspector = NetworkInspector(network_rules=network_rules)
    engine = RuleEngine(policy_path=POLICY_PATH)

    callback = build_callback(packet_parser, inspector, engine)

    if args.dry_run:
        print("[warden-sidecar] Running in --dry-run mode", flush=True)
        raw_bytes = sys.stdin.buffer.read()
        if not raw_bytes:
            print("No bytes received on stdin.", file=sys.stderr)
            sys.exit(0)
            
        class MockPacket:
            def __init__(self, payload): self._payload = payload
            def get_payload(self): return self._payload
            def accept(self): print("ACTION: ACCEPT")
            def drop(self): print("ACTION: DROP")
            
        callback(MockPacket(raw_bytes))
        sys.exit(0)

    # Full NFQUEUE mode
    setup_iptables(queue_num=NFQUEUE_NUM)
    atexit.register(teardown_iptables, NFQUEUE_NUM)

    nfqueue = netfilterqueue.NetfilterQueue()
    nfqueue.bind(NFQUEUE_NUM, callback)

    print(f"[warden-sidecar] Listening on NFQUEUE {NFQUEUE_NUM}...", flush=True)
    try:
        nfqueue.run()
    except KeyboardInterrupt:
        print("\n[warden-sidecar] Shutting down...")
    finally:
        nfqueue.unbind()


if __name__ == "__main__":
    main()
