#!/usr/bin/env python3
"""
sidecar/interceptor.py — Warden Network Sidecar Interceptor

CONTRACT: This is the entry point for the warden-sidecar container.
It intercepts outbound network traffic from the jail using NFQUEUE.
"""

import os
import sys
import argparse
import subprocess
import atexit
import yaml

try:
    import netfilterqueue  # type: ignore
except ImportError:
    pass

from daemon.parser.packet_parser import PacketParser
from daemon.inspectors.network_inspector import NetworkInspector
from daemon.rules.engine import RuleEngine
from daemon.ledger.logger import Logger as LedgerLogger, LedgerEvent
from daemon.executors.base import ExecutionResult
from daemon.inspectors.base import Decision

LEDGER_PATH = os.environ.get("WARDEN_LEDGER_PATH", "/data/ledger/warden.db")
POLICY_PATH = os.environ.get("WARDEN_POLICY_PATH", "daemon/rules/policy.yaml")
NFQUEUE_NUM = 0


def verify_environment() -> bool:
    """Verify the container environment before attempting NFQUEUE work."""
    ok = True
    ledger_dir = os.path.dirname(LEDGER_PATH)
    if not os.path.isdir(ledger_dir):
        print(f"[warden-sidecar] ERROR: ledger directory {ledger_dir!r} does not exist.", file=sys.stderr, flush=True)
        ok = False
    else:
        canary = os.path.join(ledger_dir, ".sidecar_write_check")
        try:
            with open(canary, "w") as f:
                f.write("ok")
            os.remove(canary)
        except OSError as e:
            print(f"[warden-sidecar] ERROR: cannot write to ledger directory: {e}", file=sys.stderr, flush=True)
            ok = False

    try:
        import netfilterqueue  # type: ignore # noqa: F401
    except ImportError as e:
        print(f"[warden-sidecar] ERROR: cannot import netfilterqueue: {e}", file=sys.stderr, flush=True)
        ok = False
    except OSError as e:
        print(f"[warden-sidecar] ERROR: netfilterqueue import raised OSError: {e}", file=sys.stderr, flush=True)
        ok = False

    return ok


def setup_iptables(queue_num: int) -> None:
    """
    Insert iptables rule to redirect traffic to NFQUEUE.

    WHY OUTPUT (not FORWARD): The sidecar shares the jail's network namespace
    (`network_mode: "service:jail"` in docker-compose.yml). From the perspective
    of this shared namespace, packets generated by the jail's processes originate
    locally. They therefore traverse the OUTPUT chain. The FORWARD chain only
    applies to packets being routed *through* the namespace from one interface
    to another, which is not what the jail is doing.
    """
    print(f"[warden-sidecar] Inserting iptables rule on OUTPUT chain for queue {queue_num}...", flush=True)
    subprocess.run(
        ["iptables", "-I", "OUTPUT", "-j", "NFQUEUE", "--queue-num", str(queue_num)],
        check=True
    )


def teardown_iptables(queue_num: int) -> None:
    """Remove the iptables rule on exit."""
    print(f"[warden-sidecar] Removing iptables rule for queue {queue_num}...", flush=True)
    subprocess.run(
        ["iptables", "-D", "OUTPUT", "-j", "NFQUEUE", "--queue-num", str(queue_num)],
        check=False  # Ignore errors if rule is already gone
    )


def build_callback(parser: PacketParser, inspector: NetworkInspector, engine: RuleEngine, logger: LedgerLogger):
    """Factory to build the packet callback with closed-over dependencies."""
    def packet_callback(packet) -> None:
        raw_bytes = packet.get_payload()
        
        # 1. Parse
        try:
            parsed = parser.parse(raw_bytes)
        except Exception:
            # If we absolutely cannot parse it, drop it as malformed.
            packet.drop()
            return

        # 2. Inspect
        verdict = inspector.inspect(parsed)
        
        # 3. Evaluate
        final_verdict = engine.evaluate(parsed, [verdict] if verdict else [])
        
        # 4. Log
        # Network events produce no stdout/stderr or subprocess exit codes.
        result = ExecutionResult(stdout="", stderr="", exit_code=0, was_real=False, was_fabricated=False)
        event = LedgerEvent(
            raw_input=parsed.raw_input,
            parsed_action=parsed,
            verdict=final_verdict,
            result=result,
            event_type="network"
        )
        logger.record(event)
        
        # 5. Enforce
        if final_verdict.decision == Decision.ALLOW:
            packet.accept()
        else:
            packet.drop()
            
    return packet_callback


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Read packet bytes from stdin instead of NFQUEUE")
    args = parser.parse_args()

    if not args.dry_run and not verify_environment():
        print("[warden-sidecar] environment checks FAILED", file=sys.stderr, flush=True)
        sys.exit(1)

    print("[warden-sidecar] Loading components...", flush=True)
    
    with open(POLICY_PATH, "r") as f:
        policy_doc = yaml.safe_load(f)
    network_rules = policy_doc.get("network_rules", [])

    # Instantiate the 4 pillars of the interception loop
    packet_parser = PacketParser()
    inspector = NetworkInspector(network_rules=network_rules)
    engine = RuleEngine(policy_path=POLICY_PATH)
    logger = LedgerLogger(db_path=LEDGER_PATH)

    callback = build_callback(packet_parser, inspector, engine, logger)

    if args.dry_run:
        print("[warden-sidecar] Running in --dry-run mode", flush=True)
        raw_bytes = sys.stdin.buffer.read()
        if not raw_bytes:
            print("No bytes received on stdin.", file=sys.stderr)
            sys.exit(0)
            
        class MockPacket:
            def __init__(self, payload): self._payload = payload
            def get_payload(self): return self._payload
            def accept(self): print("ACTION: ACCEPT")
            def drop(self): print("ACTION: DROP")
            
        callback(MockPacket(raw_bytes))
        sys.exit(0)

    # Full NFQUEUE mode
    setup_iptables(queue_num=NFQUEUE_NUM)
    atexit.register(teardown_iptables, NFQUEUE_NUM)

    nfqueue = netfilterqueue.NetfilterQueue()
    nfqueue.bind(NFQUEUE_NUM, callback)

    print(f"[warden-sidecar] Listening on NFQUEUE {NFQUEUE_NUM}...", flush=True)
    try:
        nfqueue.run()
    except KeyboardInterrupt:
        print("\n[warden-sidecar] Shutting down...")
    finally:
        nfqueue.unbind()


if __name__ == "__main__":
    main()
